### PR TITLE
remove trailling spaces

### PR DESCRIPTION
**Pull request by royopa**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
much better :+1:

**Comment by weaverryan** [comment]
Indeed better! Though I think now I'm going to remove much of the README and link over to https://knpuniversity.com/screencast/guard instead - in order to avoid duplication (this stuff is already a little out of date). Thanks!

**Comment by bocharsky-bw** [comment]
Nevertheless, I think it will be a very good to hold important parts of documentation into the bundle docs.

**Comment by weaverryan** [comment]
@bocharsky-bw I'll make a pull request when I update the README - we'll try to strike the balance between duplication and having too little (because I agree with your point).

**Comment by royopa** [comment]
I created the repository with some examples for README in PHP Projects. 
The idea is keep the basics information for the project and maybe a link to documentation.
Please, see the repository and contributions are welcome!
https://github.com/royopa/PHProjectsReadme

**Comment by bocharsky-bw** [comment]
@royopa You're right here, some sections like `installation` and `usage` should be in a good project, but in a various forms. For example, if installation section is large - it could be moved to different file, for example, `installation.md`. Some frameworks, like `Symfony`, wants  all docs to be stored in `Resources/docs` directory, etc. Also documentation could be in `rst` format like in `Symfony` framework.

Anyway, I think a content of README file could a bit complicated and depends on projects. So there are no a single template for all projects. This is only documentation, not PHP (or other languages) code with _strict_ architecture dictates by frameworks, and the main task of it is to write documentation in clear and understandable way.

**Pull request merged**
